        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 16 10:48:23 2018
        MODULE CALC_CURRENT_DIVB__genmod
          INTERFACE 
            SUBROUTINE CALC_CURRENT_DIVB
            END SUBROUTINE CALC_CURRENT_DIVB
          END INTERFACE 
        END MODULE CALC_CURRENT_DIVB__genmod
