        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 16 10:48:23 2018
        MODULE GREEN_FUNCTION_METHOD__genmod
          INTERFACE 
            SUBROUTINE GREEN_FUNCTION_METHOD
            END SUBROUTINE GREEN_FUNCTION_METHOD
          END INTERFACE 
        END MODULE GREEN_FUNCTION_METHOD__genmod
