        !COMPILER-GENERATED INTERFACE MODULE: Thu Aug 16 10:48:23 2018
        MODULE COORD_INIT__genmod
          INTERFACE 
            SUBROUTINE COORD_INIT
            END SUBROUTINE COORD_INIT
          END INTERFACE 
        END MODULE COORD_INIT__genmod
